In [1]:
import pandas as pd
import yfinance as yf

In [2]:
nifty = yf.download("^NSEI", start="2022-01-01")['Close']

nifty_weekly = nifty.resample('W-FRI').last().dropna()
nifty_weekly

[*********************100%***********************]  1 of 1 completed

Ticker             ^NSEI
Date
2022-01-07  17812.699219
2022-01-14  18255.750000
2022-01-21  17617.150391
2022-01-28  17101.949219
2022-02-04  17516.300781
...                  ...
2026-08-28  24175.650391
2026-09-04  23897.699219
2026-09-11  23398.099609
2026-09-18  23346.400391
2026-09-25  23140.500000

[247 rows x 1 columns]

In [3]:
nifty_weekly.columns

Index(['^NSEI'], dtype='str', name='Ticker')

In [4]:
nifty_df = nifty_weekly.reset_index()
nifty_df.columns = ["Date", "Nifty_50"]
nifty_df

          Date      Nifty_50
0   2022-01-07  17812.699219
1   2022-01-14  18255.750000
2   2022-01-21  17617.150391
3   2022-01-28  17101.949219
4   2022-02-04  17516.300781
..         ...           ...
242 2026-08-28  24175.650391
243 2026-09-04  23897.699219
244 2026-09-11  23398.099609
245 2026-09-18  23346.400391
246 2026-09-25  23140.500000

[247 rows x 2 columns]

In [5]:
nifty_df.to_csv('data/nifty_50.csv', index=False)